### ISSUE TITLE
Service Weighting data

### ISSUE THREAD

**Issue by ClairePUK** [ParkisonsUK-fuse/what3things#15]
https://docs.google.com/spreadsheets/d/1C8EnClau1qLXGc3OJ8A0CQ6noKGokNHogzuhQv2863E/edit?usp=sharing

The process
- The user is shown nine quotes one-by-one from people who have recently been diagnosed with Parkinson’s
- For each quote the user picks whether they relate to that quote or not 
- Each quote represents one service (primary) and up to two other services (secondary)
- From the quotes chosen, the relevant services are displayed as recommendations to the user

The rules
- Only three services will be recommended to the user
- If more than three quotes have been chosen by the user, any quote where a service appears as a secondary AND a primary, the secondary instance will be overwritten by the primary quote
- Four services can be shown in the rare occurrence of no service appearing more than once, either as a primary or a secondary
- If a user is under 50 then whatever their recommendations, they will also be recommended the early onset page
- If a user only chooses one quote then all services (both primary and secondary associated with that quote) are shown to the user as recommendations
- If the third service spot is empty after the above criteria are fulfilled then ‘Parkinson’s nurse’ should be shown to fill the gap if it isn’t already one of the recommended services

**Comment by drkane** [comment]
So one possible model would be this:

- change your scores in the google sheet so they are 1 = perfect match, 0.5 = secondary match (could do this by just doing 1/x where x is the score in the spreadsheet.
- initialise a list of the services with a value of 0 for each
- go through each statement. If it has been picked, add the value of each project to the list.
- sort the lists by the resulting values
- apply any of the other rules above.

This would be a simple implementation but it would be easy to make it more complex. Eg you could have values all along the scale: 0.3, 0.05, 0.7 etc depending on how appropriate the project is to the quote. You could also then go beyond a 0..1 scale for questions that were prioritised, so you could have a value of 2 for an important question. (or have weightings for questions).

With 8 questions there's only 256 possible options, so it's possible to have a few scenarios to test and check if they match your expected results.

**Comment by andrewMacmurray** [comment]
@drkane that sounds great, would mean we would have finer control on what gets recommended to the user

**Comment by suninthesky** [comment]
Mapping the manual classification to a [truth table](https://github.com/ParkisonsUK-fuse/what3things/files/875599/output.txt) could be useful. Could also leverage [Hamming Distance](https://en.wikipedia.org/wiki/Hamming_distance), though the priority of identical hamming distances would need thinking about.

Q1 | Q2 | Q3 | Q4 | Q5 | Q6 | Q7 | Q8 | Hamming Distance | Match
-|-|-|-|-|-|-|-|-|-
0 | 1 | 1 | 1 | 0 | 1 | 0 | 0 | - | User response
0 | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 4 | Peer support service
0 | 0 | 1 | 0 | 0 | 0 | 1 | 0 | 4 | Forum
0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 2 | Helpline

**Comment by andrewMacmurray** [comment]
@suninthesky I'm not quite sure I understand, how does the hamming distance relate to weighting? Could you perhaps go into more detail?

**Comment by suninthesky** [comment]
@andrewMacmurray apologies, should have clarified that it doesn't... 

> the priority of identical hamming distances would need thinking about

...as it assumes a boolean data type (feels like less mental overhead for the person classifying services). Just another way to look at the problem, and would be interesting to compare the results hamming distance yields vs. the weights table e.g.

. | Q1 | Q2 | Q3 | Q4 | Weights Sum | Hamming Distance
-|-|-|-|-|-|-
 User input (boolean value) | Disagree (false) | Agree (true) | Agree (true) | Agree (true) | - | -
Service 1 weights (boolean value) | 1 (true) | 2 (true) | 1 (true) | 0 (false) | 3 | 2
Service 2 weights (boolean value) | 0 (false) | 0 (false) | 2 (true) | 1 (true) | 3 | 1

[Testing the weighting data](https://github.com/ParkisonsUK-fuse/what3things/issues/20) against a truth table [(now 512x512)](https://github.com/ParkisonsUK-fuse/what3things/files/881301/output.txt) would be how I'd start comparing approaches.

**Comment by ClairePUK** [comment]
@ivanmauricio @andrewMacmurray

Version 4 is ready

https://docs.google.com/spreadsheets/d/1C8EnClau1qLXGc3OJ8A0CQ6noKGokNHogzuhQv2863E/edit#gid=1595556060

**Comment by ClairePUK** [comment]
closed with pr #54
