### ISSUE TITLE
Deployment Options

### ISSUE THREAD

**Issue by ivanmauricio** [ParkisonsUK-fuse/what3things#24]
We need to decide between Heroku and AWS.

# Heroku

## Pros

* It's free.
* Very easy to set up.
 
## Cons

* Site needs to wake up if it has not been used within the last half hour (this usually takes around 30 seconds). This could be mitigated by paying for a dyno.

# AWS

## Pros

* It's very fast.
* No startup time.

## Cons

* Paid for.
* More difficult set up.

**Comment by ivanmauricio** [comment]
@ClairePUK We have spent a few painful hours trying to set up AWS and have not finished unfortunately. However we managed to deploy to Heroku within 15 minutes so we think this may be the most time effective option. We have had a look at pricing and it should be around $20/month. What do you think?

**Comment by ClairePUK** [comment]
@ivanmauricio @andrewMacmurray Thanks for looking into this guys. Julie's happy to pay, but would it be okay just to get a couple of sentences on why the paid version is better for us than the free version? And is there an option to switch over once things are set-up? Cheers!

**Comment by andrewMacmurray** [comment]
@ClairePUK so to summarise with downsides of using the Heroku free tier:

+ when the app hasn't been used for half an hour, the app "goes to sleep", what this means is that the next user who accesses the app will have a slight loading time (around 5-8s). After that though any other users that access the app will see it load much faster.
+ We could monitor how this goes when you're testing the app and if if becomes a problem we can always pay to get rid of the initial load time (this will be around $10/month)
