### ISSUE TITLE
Email results

### ISSUE THREAD

**Issue by ClairePUK** [ParkisonsUK-fuse/what3things#5]
I would like my results emailed to me so I can have my own copy to keep and revisit or send to family and friends.

**Comment by ClairePUK** [comment]
![dsc_0058](https://cloud.githubusercontent.com/assets/26407154/25267548/1ef41312-266d-11e7-91d5-fa549f26b282.JPG)

**Comment by andrewMacmurray** [comment]
closed with pr #99
