### ISSUE TITLE
Postcode - not optional 

### ISSUE THREAD

**Issue by ClairePUK** [ParkisonsUK-fuse/what3things#80]
Users cannot progress until they put in a postcode - what happens if they try to skip this?

**Comment by andrewMacmurray** [comment]
@ClairePUK I thought we were saying this was not optional

**Comment by andrewMacmurray** [comment]
https://github.com/ParkisonsUK-fuse/what3things/issues/13

**Comment by ClairePUK** [comment]
@andrewMacmurray Yes that's what I mean. What happens if they try to skip this? Will they get an error message? Will it move off the page? Or do we need to make sure this is included in the copy?

**Comment by andrewMacmurray** [comment]
@ClairePUK it's not possible for them to skip this, they can't actually get to the next page

**Comment by ClairePUK** [comment]
Will there be a error message?

**Comment by andrewMacmurray** [comment]
the button is greyed out until they enter a valid postcode, did you have something different in mind for this?

**Comment by ClairePUK** [comment]
That's fine - we'll make sure the copy says this isnt optional. Cheers!
