### ISSUE TITLE
Email Spike

### ISSUE THREAD

**Issue by ivanmauricio** [ParkisonsUK-fuse/what3things#93]
We need to figure out how to send emails using Phoenix. The core areas to research are -

* Providers
* Templates
* Analytics

**Comment by andrewMacmurray** [comment]
https://github.com/thoughtbot/bamboo

**Comment by andrewMacmurray** [comment]
https://www.dailydrip.com/topics/elixirsips/drips/bamboo-email

**Comment by ivanmauricio** [comment]
Closed as this went very well 😎
